/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Affandhy
 */
public class ProgramAritmatika extends javax.swing.JFrame {

    String jns = "" ;
    int jml ;
    
    /**
     * Creates new form ProgramAritmatika
     */
    public ProgramAritmatika() {
        initComponents();
        panel.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel = new javax.swing.JPanel();
        c = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        jmlbl = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        d = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        ket = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PROGRAM ARITMATIKA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 10, 240, 40);

        panel.setBackground(new java.awt.Color(153, 153, 255));
        panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Operasi"));
        panel.setLayout(null);

        c.setText("Bilangan 3");
        panel.add(c);
        c.setBounds(20, 130, 100, 40);

        jLabel3.setText("Jumlah Bilangan");
        panel.add(jLabel3);
        jLabel3.setBounds(20, 20, 100, 40);

        a.setText("Bilangan 1");
        panel.add(a);
        a.setBounds(20, 60, 100, 40);

        b.setText("Bilangan 2");
        panel.add(b);
        b.setBounds(20, 90, 100, 40);

        jmlbl.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        jmlbl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmlblActionPerformed(evt);
            }
        });
        panel.add(jmlbl);
        jmlbl.setBounds(150, 30, 160, 30);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panel.add(jTextField1);
        jTextField1.setBounds(150, 130, 160, 30);
        panel.add(jTextField2);
        jTextField2.setBounds(150, 70, 160, 30);
        panel.add(jTextField3);
        jTextField3.setBounds(150, 100, 160, 30);
        panel.add(jTextField4);
        jTextField4.setBounds(150, 210, 160, 60);

        d.setText("Bilangan 3");
        panel.add(d);
        d.setBounds(20, 160, 100, 40);

        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel.add(jButton1);
        jButton1.setBounds(20, 210, 80, 60);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        panel.add(jTextField5);
        jTextField5.setBounds(150, 160, 160, 30);
        panel.add(ket);
        ket.setBounds(100, 280, 110, 40);

        jPanel1.add(panel);
        panel.setBounds(30, 100, 330, 340);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--METODE--", "Perkalian", "Pembagian", "Penambahan", "Pengurangan" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(250, 60, 110, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 410);

        setBounds(0, 0, 416, 444);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jmlblActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmlblActionPerformed
        // TODO add your handling code here:
        settext() ;
        //if(jComboBox1.getSelectedItem().equals("1"))
        //{
            //jTextField1.hide();
            //jTextField3.hide();
          //  k.hide();
        //}
        
        //else if(jComboBox1.getSelectedItem().equals("2"))
        //{
            //jTextField1.hide();
          //  k.hide();
        //}
        //else if(jComboBox1.getSelectedItem().equals("3"))
       // {
         //   k.hide();
        //}
    }//GEN-LAST:event_jmlblActionPerformed

    public void settext() {
        if(jmlbl.getSelectedItem().equals("1"))
        {
            jTextField1.hide();
            jTextField3.hide();
            jTextField5.hide();
            b.hide();
            c.hide();
            d.hide();
            jml = 3 ;
        }
        
        else if(jmlbl.getSelectedItem().equals("2"))
        {
            jTextField1.hide();
            jTextField5.hide();
            c.hide();
            d.hide();
            
            jml = 2 ;
        }
        else if(jmlbl.getSelectedItem().equals("3"))
        {
            jTextField5.hide();
            c.hide();
            
            jml = 1 ;
        }
        else if(jmlbl.getSelectedItem().equals("4"))
        {
            
            jml = 4 ;
        }
        
    }
    
    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        setjenis();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    
    public void setjenis() {     
   
        if(jComboBox2.getSelectedItem().equals("Perkalian"))
        {
            jns="perkalian" ;
            ket.setText("perkalian");
            jmlbl.setEnabled(true);
            panel.setVisible(true);
        }
        else if(jComboBox2.getSelectedItem().equals("Pembagian"))
        {
            jns="pembagian" ;
            ket.setText("pembagian");
            jmlbl.setEnabled(true);
            panel.setVisible(true);   
        }
        else if(jComboBox2.getSelectedItem().equals("Penambahan"))
        {
            jns="penambahan" ;
            ket.setText("penambahan");
            jmlbl.setEnabled(true);
            panel.setVisible(true);
            
        }
        else if(jComboBox2.getSelectedItem().equals("Pengurangan"))
        {
            jns="pengurangan" ;
            ket.setText("pengurangan");
            jmlbl.setEnabled(true);
            panel.setVisible(true);
            
        } 
        else
        {
            jns = null ;
            panel.setVisible(false);
            
        }
        }

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        Double hasil = 0.0 ; 
        Double a1,a2,a3,a4  ;
        
        a1 = Double.parseDouble(jTextField2.getText()) ;
        a2 = Double.parseDouble(jTextField3.getText()) ;
        
      
        
        if(jns.equals("perkalian"))
        {
            if(jml == 2)
            {
                hasil = a1*a2 ;
                jTextField4.setText(a1+"*"+a1+"="+hasil);   
            }
            
            if(jml == 3)
            {
                a3 = Double.parseDouble(jTextField1.getText()) ;
        
             
                hasil = a1*a2*a3 ;
                jTextField4.setText(a1+"*"+a2+"*"+a3+"="+hasil);
                
            }
            
            
            if(jml == 4)
            {
                a3 = Double.parseDouble(jTextField1.getText()) ;
        a4 = Double.parseDouble(jTextField5.getText()) ;
             
                hasil = a1 * a2 * a3 * a4 ;
                jTextField4.setText(a1+"*"+a2+"*"+a3+"*"+a4+"="+hasil);
                
            }
            
        }
        if(jns.equals("pembagian"))
        {
            if(jml == 2)
            {
              
                hasil = a1 / a2 ;
                jTextField4.setText(a1+"/"+a1+"="+hasil);  
                
            }
            
            if(jml == 3)
            {
             a3 = Double.parseDouble(jTextField1.getText()) ;
        
                hasil = a1 / a2 / a3 ;
                jTextField4.setText(a1+"/"+a2+"/"+a3+"="+hasil);
                
            }
            
            
            if(jml == 4)
            {
             a3 = Double.parseDouble(jTextField1.getText()) ;
        a4 = Double.parseDouble(jTextField5.getText()) ;
                hasil = a1 / a2 / a3 / a4 ;
                jTextField4.setText(a1+"/"+a2+"/"+a3+"/"+a4+"="+hasil);
                
            }
            
        }
        
        
        if(jns.equals("penambahan"))
        {
            if(jml == 2)
            {
              
                hasil = a1 + a2 ;
                jTextField4.setText(a1+"+"+a1+"="+hasil);  
                
            }
            
            if(jml == 3)
            {
             a3 = Double.parseDouble(jTextField1.getText()) ;
        
                hasil = a1 + a2 + a3 ;
                jTextField4.setText(a1+"+"+a2+"+"+a3+"="+hasil);
                
            }
            
            
            if(jml == 4)
            {
             a3 = Double.parseDouble(jTextField1.getText()) ;
        a4 = Double.parseDouble(jTextField5.getText()) ;
                hasil = a1 + a2 + a3 + a4 ;
                jTextField4.setText(a1+"+"+a2+"+"+a3+"+"+a4+"="+hasil);
                
            }
            
        }
        if(jns.equals("pengurangan"))
        {
            if(jml == 2)
            {
              
                hasil = a1 - a2 ;
                jTextField4.setText(a1+"-"+a1+"="+hasil);  
                
            }
            
            if(jml == 3)
            {
             a3 = Double.parseDouble(jTextField1.getText()) ;
                hasil = a1-a2-a3 ;
                jTextField4.setText(a1+"-"+a2+"-"+a3+"="+hasil);
                
            }
            
            
            if(jml == 4)
            {
             a3 = Double.parseDouble(jTextField1.getText()) ;
        a4 = Double.parseDouble(jTextField5.getText()) ;
                hasil = a1-a2-a3-a4 ;
                jTextField4.setText(a1+"-"+a2+"-"+a3+"-"+a4+"="+hasil);
                
            }
            
        }
        
      //  perkalian() ;
      //  pembagian() ;
       // pemambahan() ;
       // pengurangan() ;
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramAritmatika.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramAritmatika().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel a;
    private javax.swing.JLabel b;
    private javax.swing.JLabel c;
    private javax.swing.JLabel d;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JComboBox jmlbl;
    private javax.swing.JLabel ket;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables

   

}
